apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-collector
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: opentelemetry-collector
      version: 0.92.0
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: opentelemetry-values
      valuesKey: values.yaml
