apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-collector
  namespace: monitoring
spec:
  releaseName: opentelemetry-collector
  chart:
    spec:
      chart: opentelemetry-collector
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: flux-system
  interval: 5m
  valuesFrom:
  - kind: ConfigMap
    name: otel-values
    valuesKey: values.yaml
