apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - helmrelease-opentelemetry-collector.yaml

configMapGenerator:
  - name: otel-values
    files:
      - values.yaml

generatorOptions:
  disableNameSuffixHash: true
