apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mi-chart
  namespace: react-app
spec:
  interval: 1m
  chart:
    spec:
      chart: mi-chart
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: mi-chart-repo
        namespace: flux-system`
  valuesFrom:
    - kind: ConfigMap
      name: react-values
      valuesKey: values.yaml`