apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mi-chart
  namespace: react-app
spec:
  interval: 1m
  chart:
    spec:
      chart: mi-chart
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: mi-chart-repo
        namespace: flux-system
  values:
    replicaCount: 1
    image:
      repository: docker.io/toni1997/my-react-app
      tag: latest
      pullPolicy: Always
    service:
      type: NodePort
      port: 80
      targetPort: 80
      nodePort: 30080
