apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: react-app
resources:
  - helmrelease-nginx.yaml
configMapGenerator:
  - name: react-app-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
