replicaCount: 1
image:
  repository: docker.io/toni1997/my-react-app
  tag: latest
  pullPolicy: Always
service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30080
opentelemetry:
  enabled: true
  collectorEndpoint: "http://opentelemetry-collector.monitoring.svc.cluster.local:4317"
