# Para usar elastic externo
# storage:
#   type: elasticsearch
#   options:
#     es:
#       server-urls: http://elasticsearch.monitoring.svc.cluster.local:9200

provisionDataStore:
  cassandra: false
  elasticsearch: false
  kafka: false

storage:
  type: badger
  options:
    badger:
      directory-key: /badger/key
      directory-value: /badger/data

collector:
  enabled: true
  service:
    type: ClusterIP
  options:
    span-storage.type: badger
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 128Mi
      cpu: 100m
  extraVolumes:
    - name: badger-data
      emptyDir: {}
  extraVolumeMounts:
    - name: badger-data
      mountPath: /badger

query:
  enabled: true
  service:
    type: ClusterIP
  options:
    span-storage.type: badger
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 128Mi
      cpu: 100m
  extraVolumes:
    - name: badger-data
      emptyDir: {}
  extraVolumeMounts:
    - name: badger-data
      mountPath: /badger

agent:
  enabled: true
  nameOverride: custom-agent
  strategy: DaemonSet
  resources:
    requests:
      memory: 32Mi
      cpu: 25m
    limits:
      memory: 64Mi
      cpu: 50m

ui:
  enabled: true
  