# replicas: 1
# minimumMasterNodes: 1

# esJavaOpts: "-Xms512m -Xmx512m"

# volumeClaimTemplate:
#   storageClassName: standard
#   accessModes: ["ReadWriteOnce"]
#   resources:
#     requests:
#       storage: 10Gi

# resources:
#   requests:
#     cpu: 200m
#     memory: 1Gi
#   limits:
#     cpu: 300m
#     memory: 1.5Gi
